# MySQL versions 5.6 required (5.7 will not work)
defaults: &defaults
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  username: root
  password:

development:
  <<: *defaults
  database: skeleton_development

test:
  <<: *defaults
  database: skeleton_test
